name: Tag Release Version

on:
  push:
    branches:
      - master  # or your default branch like 'master'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18'  # Ensure this matches your required Node.js version

      - name: Extract version from package.json
        id: package_version
        run: echo "::set-output name=VERSION::$(cat package.json | jq -r .version)"

      - name: Create Git tag
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git tag -a "v${{ steps.package_version.outputs.VERSION }}" -m "Release version ${{ steps.package_version.outputs.VERSION }}"
          git push origin "v${{ steps.package_version.outputs.VERSION }}"
